[build]
builder = "nixpacks"
buildCommand = ""

[deploy]
startCommand = "gunicorn wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["python312"]